### ISSUE TITLE
Update goo.gl links

### ISSUE THREAD

**Issue by neolivz** [pact-foundation/pact-workshop-dotnet-core-v1#11]
There is a lot of goo.gl URL links in the readme. Since Google has shut down the URL shorner service the links will become inaccessible by April 2020. Need to update the links, if there is no update on documentation by then.

**Comment by tdshipley** [comment]
Thanks for this - I will make a note to update the links.

**Comment by YOU54F** [comment]
>Google has shut down the URL shorner service the links will become inaccessible by April 2020.

The service is still active today and honouring the old urls. however that being said I have replaced the URL's to their resolved counterparts
