### ISSUE TITLE
Request: Upgrade to latest workshop format

### ISSUE THREAD

**Issue by mefellows** [pact-foundation/pact-workshop-dotnet-core-v1#17]
Thanks so much for this workshop, it seems very popular!

It would be great to have the workshop upgraded to match the latest "canonical" standard: https://github.com/pact-foundation/pact-workshop-js.

Would you also be willing to move this to the pact-foundation repository, with you as the admin?

**Comment by YOU54F** [comment]
see https://github.com/pact-foundation/pact-workshop-dotnet-core-v1/pull/25

main text needs updating with updated code snippets but the tested solution is upgraded to use the pact-net 4.5.0

additional contributions are welcome!
